# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexpense',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
